### ISSUE TITLE
So excited to try this out

### ISSUE THREAD

**Issue by vergenzt** [zyedidia/knit#2]
I just read through the readme and docs files and I just wanted to say that I'm so excited to try this tool out for personal projects. I've thought for a while that Make has needed a rewrite to soften some of its rough edges, and this project seems to keep the best parts of Make while simplifying and standardizing the parts that have always bothered me.

Thanks for making (or should I say "knitting"?!? 😂 ) this!

**Comment by zyedidia** [comment]
Awesome! I hope it's useful for you and let me know if you run into problems!
